In [1]:
# Load the dataset
import pandas as pd

# Filter the DataFrame based on the match_type
match_type = input("Enter Match Type:")

# Filter the DataFrame based on the gender
gender = input("Enter Gender:")

In [2]:
import pandas as pd
df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_df_cleaned.csv")
df.drop(columns=["Unnamed: 0","event_name"], inplace=True)
df = df[(df["winner"] == df["team1"]) | (df["winner"] == df["team2"])]
df.sort_values(by="match_date", ascending=False, ignore_index=True,inplace=True)
print("Length of Data Frame:", len(df))
df[:5]

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\GITHUB\\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\\source_data\\Summary\\match_summary\\male\\0_male_match_summary_df_cleaned.csv'

In [ ]:
df["event"].unique()

array(['T20I', 'Vitality Blast',
       'Cricket Ireland Inter-Provincial Twenty20 Trophy', 'IPL',
       'Central American Cricket Championships', 'Pakistan Super League',
       'CSA T20 Challenge', 'Bangladesh Premier League',
       'International League T20', 'SA20', 'Super Smash',
       'Big Bash League', 'Syed Mushtaq Ali Trophy',
       "South American Men's Championships", 'Caribbean Premier League',
       "The Hundred Men's Competition", 'Lanka Premier League',
       'Major League Cricket', 'Mzansi Super League',
       'Afghanistan Premier League'], dtype=object)

In [ ]:
# Filter the DataFrame based on the event
event = input("Enter Event Name: ")

In [ ]:
df = df[(df["event"]  == event)]
print("Length of Data Frame: ",len(df))
df[:5]

Length of Data Frame:  2520

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1438262,2024,T20I,2024-06-16,Norway,Finland,Finland,bat,Norway,100,100,60,25,4,1,"Kerava National Cricket Ground, Kerava"
1,1436493,2024,T20I,2024-06-16,Portugal,Isle Of Man,Portugal,bat,Portugal,100,100,33,0,2,2,"Roma Cricket Ground, Spinaceto"
2,1436491,2024,T20I,2024-06-16,Luxembourg,Israel,Luxembourg,bat,Israel,0,0,50,100,1,2,"Roma Cricket Ground, Spinaceto"
3,1436492,2024,T20I,2024-06-16,France,Austria,Austria,field,Austria,0,0,0,100,3,4,"Simar Cricket Ground, Rome"
4,1438074,2024,T20I,2024-06-16,Jersey,Denmark,Denmark,field,Jersey,100,100,100,54,3,0,"Svanholm Park, Brondby"

In [ ]:
df["team2"].unique()

array(['Finland', 'Isle Of Man', 'Israel', 'Austria', 'Denmark',
       'Romania', 'Hungary', 'Luxembourg', 'Turkey', 'Italy', 'France',
       'India', 'Australia', 'Pakistan', 'Bangladesh', 'Oman', 'Uganda',
       'Netherlands', 'Canada', 'Afghanistan', 'Namibia',
       'United States Of America', 'Papua New Guinea', 'Nepal',
       'South Africa', 'West Indies', 'England', 'Bulgaria', 'Gibraltar',
       'Ireland', 'Belgium', 'Japan', 'Indonesia', 'New Zealand',
       'Hong Kong', 'Kuwait', 'United Arab Emirates', 'Qatar', 'Bahrain',
       'Malaysia', 'Cambodia', 'Jersey', 'Kenya', 'Nigeria', 'Ghana',
       'Tanzania', 'Scotland', 'Vanuatu', 'Bhutan', 'Saudi Arabia',
       'China', 'Maldives', 'Singapore', 'Thailand', 'Sri Lanka',
       'Rwanda', 'Argentina', 'Bermuda', 'Estonia', 'Cayman Islands',
       'Mongolia', 'Malta', 'Germany', 'Croatia', 'Philippines',
       'Myanmar', 'Switzerland', 'Serbia', 'Botswana', 'Czech Republic',
       'Bahamas', 'Cameroon', 'Gambia', 'Eswatini', 'Mozambique',
       'Sierra Leone', 'Seychelles', 'Malawi', 'Lesotho', 'St Helena',
       'Mali', 'Cook Islands', 'Fiji', 'Samoa', 'Slovenia', 'Guernsey',
       'Norway', 'Sweden', 'Cyprus', 'Greece', 'Portugal', 'Spain',
       'Belize', 'Panama', 'Icc World Xi', 'Zimbabwe'], dtype=object)

In [ ]:
df.isnull().sum()

match_id                 0
season                   0
event                    0
match_date               0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
winner                   0
h2h_team1_wins%          0
h2h_venue_team1_wins%    0
team1_venue_wins%        0
team2_venue_wins%        0
team1_last_5_wins        0
team2_last_5_wins        0
ground                   0
dtype: int64

In [ ]:
df.columns

Index(['match_id', 'season', 'event', 'match_date', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'h2h_team1_wins%',
       'h2h_venue_team1_wins%', 'team1_venue_wins%', 'team2_venue_wins%',
       'team1_last_5_wins', 'team2_last_5_wins', 'ground'],
      dtype='object')

### **Feature Selection**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

# Load the dataset

summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_df_cleaned.csv")

# Filter the DataFrame based on the event
summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])

# Split dataset into features (X) and target variable (y)
X = X_encoded.drop(columns=["Unnamed: 0", 'match_id', 'season', 'match_date', "winner", "event_name", "event"])
y = pd.get_dummies(summary_df1['winner'])  # One-hot encoding for multi-class classification

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training
rf_model.fit(X_train, y_train)

# Get feature importances and sort them
feature_importances = rf_model.feature_importances_
sorted_indices = feature_importances.argsort()[::-1]  # Reverse order to get descending ranks

# Create a DataFrame to store feature names and their ranks
feature_ranks_df = pd.DataFrame({'Feature': X.columns[sorted_indices], 'Rank': range(1, len(X.columns) + 1)})

# Perform feature selection based on feature importances
selector = SelectFromModel(rf_model, threshold='median')
selector.fit(X_train, y_train)

# Transform the datasets to keep only selected features
X_train_selected = selector.transform(X_train)
X_test_selected = selector.transform(X_test)

# Print top 10 feature ranks
print("Top 10 Feature Ranks:")
feature_ranks_df.head(10)

Top 10 Feature Ranks:

                 Feature  Rank
0  h2h_venue_team1_wins%     1
1      team1_venue_wins%     2
2      team2_venue_wins%     3
3        h2h_team1_wins%     4
4      team2_last_5_wins     5
5      team1_last_5_wins     6
6    toss_decision_field     7
7      toss_decision_bat     8
8      team2_Afghanistan     9
9           team1_Uganda    10

### **Modelling**

### **Random Forest & XGB Classifier**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, balanced_accuracy_score, f1_score

# Load the dataset
summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_df_cleaned.csv")

summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
le = LabelEncoder()
summary_df1['winner'] = le.fit_transform(summary_df1['winner'])

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])
X = X_encoded.drop(columns=["Unnamed: 0", 'match_id', 'season', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training - Random Forest
rf_model.fit(X_train, y_train)

# Model Evaluation - Random Forest
y_pred_rf = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Model Evaluation:")
print("--------------------------------------------------")
print(f"Random Forest Accuracy: {rf_accuracy * 100:.2f}%")
# Evaluate the model using advanced metrics
#print("Classification Report:")
#print(classification_report(y_test, y_pred_rf, zero_division=1))

#print("Confusion Matrix:")
#print(confusion_matrix(y_test, y_pred_rf))

#print("Balanced Accuracy Score:")
#balanced_acc = balanced_accuracy_score(y_test, y_pred_rf)
#print(f"Balanced Accuracy: {balanced_acc * 100:.2f}%")

#print("F1 Score:")
#f1 = f1_score(y_test, y_pred_rf, average='weighted')
#print(f"F1 Score: {f1 * 100:.2f}%")

Random Forest Model Evaluation:
--------------------------------------------------
Random Forest Accuracy: 71.43%

### **XGB Classifier**

In [ ]:
# Ensure classes are encoded from 0 to n-1
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'], drop_first=True)
X = X_encoded.drop(columns=["Unnamed: 0", 'season',  'match_id', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Realign X to match indices of y (in case any indices were dropped)
X = X.loc[y.index]

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure y_train and y_test contain all classes
missing_classes = set(y.unique()) - set(y_train.unique())
for cls in missing_classes:
    X_train = pd.concat([X_train, X_test[y_test == cls]])
    y_train = pd.concat([y_train, y_test[y_test == cls]])

# Model Selection - XGBoost
xgb_model = XGBClassifier(eval_metric='mlogloss')

# Model Training - XGBoost
xgb_model.fit(X_train, y_train)

# Model Evaluation - XGBoost
y_pred_xgb = xgb_model.predict(X_test)
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("\nXGBoost Model Evaluation:")
print("--------------------------------------------------")
print(f"XGBoost Accuracy: {xgb_accuracy * 100:.2f}%")

XGBoost Model Evaluation:
--------------------------------------------------
XGBoost Accuracy: 75.60%

### **Teams**

In [ ]:
# Assuming df is your DataFrame
sorted_teams = sorted(set(df["team1"].unique()).union(set(df["team2"].unique())))

# Create a string with team names side by side
side_by_side = ', '.join(sorted_teams)

side_by_side

'Afghanistan, Argentina, Australia, Austria, Bahamas, Bahrain, Bangladesh, Belgium, Belize, Bermuda, Bhutan, Botswana, Bulgaria, Cambodia, Cameroon, Canada, Cayman Islands, Chile, China, Cook Islands, Croatia, Cyprus, Czech Republic, Denmark, England, Estonia, Eswatini, Fiji, Finland, France, Gambia, Germany, Ghana, Gibraltar, Greece, Guernsey, Hong Kong, Hungary, Icc World Xi, India, Indonesia, Iran, Ireland, Isle Of Man, Israel, Italy, Japan, Jersey, Kenya, Kuwait, Lesotho, Luxembourg, Malawi, Malaysia, Maldives, Mali, Malta, Mexico, Mongolia, Mozambique, Myanmar, Namibia, Nepal, Netherlands, New Zealand, Nigeria, Norway, Oman, Pakistan, Panama, Papua New Guinea, Philippines, Portugal, Qatar, Romania, Rwanda, Samoa, Saudi Arabia, Scotland, Serbia, Seychelles, Sierra Leone, Singapore, Slovenia, South Africa, South Korea, Spain, Sri Lanka, St Helena, Swaziland, Sweden, Switzerland, Tanzania, Thailand, Turkey, Uganda, United Arab Emirates, United States Of America, Vanuatu, West Indies, Zimbabwe'

### **Head-to-Head & Venue Wins**

In [ ]:
head_to_head = df[((df["team1"] == "West Indies") & (df["team2"] == "England")) | ((df["team1"] == "England") & (df["team2"] == "West Indies"))].sort_values(by="match_date",ascending=False).reset_index(drop=True)
print("Matches:",len(head_to_head))
print("Team1 Won:",len(head_to_head[head_to_head["team1"] == head_to_head["winner"]]))
#print("Team1 Venue Wins:",len(head_to_head[(head_to_head["team1"] == head_to_head["Winner"]) & (head_to_head["Ground"] == "MA Chidambaram Stadium, Chepauk, Chennai")]))
#print("Team1 Win Percentage",head_to_head["team1_win%"].unique(),"%")

head_to_head[:10]

Matches: 29
Team1 Won: 17

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1373583,2023,T20I,2023-12-21,West Indies,England,West Indies,field,West Indies,58,50,50,50,5,3,"Brian Lara Stadium, Tarouba, Trinidad, Tarouba"
1,1373582,2023,T20I,2023-12-19,West Indies,England,West Indies,field,England,58,50,50,50,5,3,"Brian Lara Stadium, Tarouba, Trinidad, Tarouba"
2,1373581,2023,T20I,2023-12-16,West Indies,England,England,field,England,58,50,37,50,5,3,"National Cricket Stadium, St George'S, Grenada"
3,1373580,2023,T20I,2023-12-14,West Indies,England,England,field,West Indies,58,50,37,50,5,3,"National Cricket Stadium, St George'S, Grenada"
4,1373579,2023,T20I,2023-12-12,West Indies,England,West Indies,field,West Indies,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"
5,1256724,2022,T20I,2022-01-30,West Indies,England,West Indies,bat,West Indies,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"
6,1256723,2022,T20I,2022-01-29,West Indies,England,West Indies,field,England,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"
7,1256722,2022,T20I,2022-01-26,West Indies,England,England,field,West Indies,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"
8,1256721,2022,T20I,2022-01-23,West Indies,England,West Indies,field,England,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"
9,1256720,2022,T20I,2022-01-22,West Indies,England,West Indies,field,West Indies,58,66,64,45,5,3,"Kensington Oval, Barbados, Bridgetown"

### **Prediction**

In [ ]:
# Future match data
future_match = pd.DataFrame({
    'team1': ['West Indies'],
    'team2': ['England'],
    'toss_winner': ['England'],
    'toss_decision': ['field'],
    'Ground': ['Darren Sammy National Cricket Stadium, Gros Islet, St Lucia'],
    'h2h_team1_wins%': [58],
    'h2h_venue_team1_wins%': [50],
    'team1_venue_wins%': [50],
    'team2_venue_wins%': [50],
    'team1_last_5_wins': [5],
    'team2_last_5_wins': [3]
})

# Encode categorical variables and ensure consistent columns with training data
future_match_encoded = pd.get_dummies(future_match, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'Ground'])

# Add missing columns for 'Ground' feature using the training data as a reference
missing_columns = list(set(X.columns) - set(future_match_encoded.columns))
future_match_encoded = pd.concat([future_match_encoded, pd.DataFrame(0, index=future_match_encoded.index, columns=missing_columns)], axis=1)

# Ensure all columns are in the correct order
future_match_encoded = future_match_encoded[X.columns]

# Make predictions for the future match
future_match_prediction = xgb_model.predict(future_match_encoded)

# Get the predicted winner's team name
predicted_winner_team_name = le.inverse_transform(future_match_prediction)[0]

print("Predicted Winner:", predicted_winner_team_name)

# Add prediction to the future_match DataFrame
future_match['predicted_winner'] = predicted_winner_team_name
future_match['actual_winner'] = " "

future_match.drop(columns=['h2h_team1_wins%', 'h2h_venue_team1_wins%', 'team1_venue_wins%','team2_venue_wins%', 'team1_last_5_wins', 'team2_last_5_wins'], inplace=True)

Predicted Winner: England

In [ ]:
import pandas as pd
import os
from datetime import datetime

# Add the TIMESTAMP column to your DataFrame
future_match['TIMESTAMP'] = datetime.now()

# Define the file path for the Excel file
file_path = rf'D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Predictions\{gender}\{event}_predictions.xlsx'

# Check if the file exists
if os.path.exists(file_path):
    # If the file exists, append the new prediction
    with pd.ExcelWriter(file_path, mode='a', engine='openpyxl', if_sheet_exists='overlay') as writer:
        # Check if the 'Predictions' sheet exists
        try:
            existing_df = pd.read_excel(file_path, sheet_name='Predictions')
            startrow = len(existing_df) + 1
        except:
            startrow = 0
        future_match.to_excel(writer, sheet_name='Predictions', index=False, header=not os.path.exists(file_path), startrow=startrow)
else:
    # If the file does not exist, create a new file and add the prediction
    with pd.ExcelWriter(file_path, mode='w', engine='openpyxl') as writer:
        future_match.to_excel(writer, sheet_name='Predictions', index=False)

print("Prediction saved to Excel file.")

Prediction saved to Excel file.

#### **Team1 Performance**

In [ ]:
team1_performance = df[((df["team1"] == "England") | (df["team2"] == "England")) ].sort_values(by='match_date', ascending=False).reset_index(drop=True)
team1_performance

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1415717,2024,T20I,2024-06-08,England,Australia,England,field,Australia,50,50,50,57,3,5,"Kensington Oval, Barbados, Bridgetown"
1,1385690,2024,T20I,2024-05-30,Pakistan,England,England,field,England,30,0,50,44,1,3,"Kennington Oval, London"
2,1385688,2024,T20I,2024-05-25,Pakistan,England,Pakistan,field,England,30,0,66,60,1,3,"Edgbaston Foundation Community Sports Ground, ..."
3,1373583,2023,T20I,2023-12-21,West Indies,England,West Indies,field,West Indies,58,50,50,50,5,3,"Brian Lara Stadium, Tarouba, Trinidad, Tarouba"
4,1373582,2023,T20I,2023-12-19,West Indies,England,West Indies,field,England,58,50,50,50,5,3,"Brian Lara Stadium, Tarouba, Trinidad, Tarouba"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,258463,2007,T20I,2007-06-28,West Indies,England,West Indies,bat,West Indies,58,60,50,44,5,3,"Kennington Oval, London"
175,249227,2007,T20I,2007-01-09,England,Australia,Australia,bat,Australia,50,0,0,63,3,5,"Sydney Cricket Ground, Sydney"
176,225263,2006,T20I,2006-08-28,Pakistan,England,England,bat,Pakistan,30,100,100,25,1,3,"County Ground, Bristol"
177,225271,2006,T20I,2006-06-15,Sri Lanka,England,Sri Lanka,bat,Sri Lanka,28,33,33,50,2,3,"The Rose Bowl, Southampton"
178,211028,2005,T20I,2005-06-13,England,Australia,England,bat,England,50,60,60,40,3,5,"The Rose Bowl, Southampton"

#### **Team2 Performance**

In [ ]:
team2_performance = df[((df["team1"] == "West Indies") | (df["team2"] == "West Indies"))].sort_values(by='match_date', ascending=False).reset_index(drop=True)
print("No of Matches: ", len(team2_performance))
team2_performance

No of Matches:  186

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1415718,2024,T20I,2024-06-08,West Indies,Uganda,West Indies,bat,West Indies,100,100,62,0,5,2,"Providence Stadium, Guyana, Providence"
1,1415702,2024,T20I,2024-06-02,Papua New Guinea,West Indies,West Indies,field,West Indies,0,0,0,100,2,5,"Providence Stadium, Guyana, Providence"
2,1433364,2024,T20I,2024-05-26,West Indies,South Africa,South Africa,bat,West Indies,50,100,66,0,5,3,"Sabina Park, Kingston, Jamaica"
3,1433363,2024,T20I,2024-05-25,West Indies,South Africa,West Indies,bat,West Indies,50,100,66,0,5,3,"Sabina Park, Kingston, Jamaica"
4,1433362,2024,T20I,2024-05-23,West Indies,South Africa,South Africa,field,West Indies,50,100,66,0,5,3,"Sabina Park, Kingston, Jamaica"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,319112,2007,T20I,2007-12-16,West Indies,South Africa,West Indies,field,West Indies,50,100,100,0,5,3,"St George'S Park, Port Elizabeth, Gqeberha"
182,287857,2007,T20I,2007-09-13,West Indies,Bangladesh,Bangladesh,field,Bangladesh,64,0,25,33,5,2,"New Wanderers Stadium, Johannesburg"
183,287853,2007,T20I,2007-09-11,West Indies,South Africa,South Africa,field,South Africa,50,33,25,50,5,3,"New Wanderers Stadium, Johannesburg"
184,258464,2007,T20I,2007-06-29,West Indies,England,West Indies,bat,England,58,60,50,44,5,3,"Kennington Oval, London"
185,258463,2007,T20I,2007-06-28,West Indies,England,West Indies,bat,West Indies,58,60,50,44,5,3,"Kennington Oval, London"

In [ ]:
# Get unique grounds
grounds = summary_df1["ground"].unique()
grounds_set = set(grounds)

# Take input for the substring
substring = input("Enter the substring: ").strip().lower()

# Filter grounds that contain the given substring
filtered_grounds = [ground for ground in grounds_set if substring in ground.lower()]
                    #] #ground.lower().startswith(substring)

print("Filtered grounds:", filtered_grounds)

Filtered grounds: ['Beausejour Stadium, Gros Islet, St Lucia', 'Darren Sammy National Cricket Stadium, Gros Islet, St Lucia']