## **üêç Python Code:**

### **Genders Are male & female**

### **Match Types Are: ODI, T20, Test, MDM, ODM**

In [1]:
import os
import pandas as pd


base_path = r"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary"

# Get genders from folders inside match_summary
genders = [folder for folder in os.listdir(base_path) if os.path.isdir(os.path.join(base_path, folder))]

# Show gender options
print("Select Gender:")
for idx, gender in enumerate(genders, start=1):
    print(f"{idx}. {gender.capitalize()}")
gender_choice = int(input("Enter choice: ").strip()) - 1
gender = genders[gender_choice]

# Get match types from filenames in the selected gender folder
gender_path = os.path.join(base_path, gender)
match_types = []
for file in os.listdir(gender_path):
    if file.endswith("_match_summary_cleaned.csv"):
        match_type = file.split("_")[0]  # e.g., 'odi' from 'odi_men_match_summary_cleaned.csv'
        if match_type not in match_types:
            match_types.append(match_type)

# Show match type options
print("\nSelect Match Type:")
for idx, mtype in enumerate(match_types, start=1):
    print(f"{idx}. {mtype.upper()}")
match_type_choice = int(input("Enter choice: ").strip()) - 1
match_type = match_types[match_type_choice]

# Confirm choices
print(f"\nGender selected: {gender.capitalize()}")
print(f"Match Type selected: {match_type.upper()}")

# Build path and load file
file_path = os.path.join(gender_path, f"{match_type}_{gender}_match_summary_cleaned.csv")
df = pd.read_csv(file_path)

df.drop(columns=["event_name"], inplace=True)
df = df[(df["winner"] == df["team1"]) | (df["winner"] == df["team2"])]
df.sort_values(by="match_date", ascending=False, ignore_index=True,inplace=True)
print("Length of Data Frame:", len(df))

# Display
df.head()

Select Gender:
1. Female
2. Male

Select Match Type:
1. IT20
2. MDM
3. ODI
4. ODM
5. T20
6. TEST

Gender selected: Male
Match Type selected: T20
Length of Data Frame: 8600

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1475270,2025,Pakistan Super League,2025-05-23,Lahore Qalandars,Islamabad United,Lahore Qalandars,bat,Lahore Qalandars,50,62,35,15,4,1,"Gaddafi Stadium, Lahore"
1,1473503,2025,IPL,2025-05-23,SRH,RCB,RCB,field,SRH,56,100,33,0,2,4,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
2,1475269,2025,Pakistan Super League,2025-05-22,Lahore Qalandars,Karachi Kings,Karachi Kings,bat,Lahore Qalandars,36,33,14,30,3,3,"Gaddafi Stadium, Lahore"
3,1473502,2025,IPL,2025-05-22,LSG,GT,GT,field,LSG,43,50,50,6,1,4,"Narendra Modi Stadium, Ahmedabad"
4,1475268,2025,Pakistan Super League,2025-05-21,Quetta Gladiators,Islamabad United,Quetta Gladiators,bat,Quetta Gladiators,55,100,22,0,5,1,"Gaddafi Stadium, Lahore"

In [2]:
df["event"].unique()

array(['Pakistan Super League', 'IPL', 'T20I', 'International League T20',
       'SA20', 'Bangladesh Premier League', 'Super Smash',
       'Big Bash League', 'Nepal Premier League',
       'Syed Mushtaq Ali Trophy',
       "ICC Men's T20 World Cup Sub Regional Africa Qualifier Group C",
       'CSA T20 Challenge', 'Caribbean Premier League',
       "ICC Men's T20 World Cup Sub Regional Africa Qualifier",
       'Vitality Blast',
       'Cricket Ireland Inter-Provincial Twenty20 Trophy',
       "ICC Men's T20 World Cup East Asia-Pacific Region Qualifier A",
       "The Hundred Men's Competition", 'Major League Cricket',
       'Lanka Premier League', 'Mzansi Super League'], dtype=object)

In [3]:
# Filter the DataFrame based on the event
event = input("Enter Event Name: ")

print("Selected Event: ", event)

df = df[(df["event"]  == event)]

print("Length of Data Frame: ",len(df))
df

Selected Event:  IPL
Length of Data Frame:  1152

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
1,1473503,2025,IPL,2025-05-23,SRH,RCB,RCB,field,SRH,56,100,33,0,2,4,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
3,1473502,2025,IPL,2025-05-22,LSG,GT,GT,field,LSG,43,50,50,6,1,4,"Narendra Modi Stadium, Ahmedabad"
5,1473501,2025,IPL,2025-05-21,MI,DC,DC,field,MI,57,72,18,16,4,1,"Wankhede Stadium, Mumbai"
7,1473500,2025,IPL,2025-05-20,RR,CSK,RR,field,RR,48,100,16,0,1,1,"Arun Jaitley Stadium, Delhi"
8,1473499,2025,IPL,2025-05-19,SRH,LSG,SRH,field,SRH,33,50,33,10,2,1,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8546,335985,2008,IPL,2008-04-20,RCB,MI,MI,bat,RCB,44,33,25,16,3,2,"Wankhede Stadium, Mumbai"
8547,335986,2008,IPL,2008-04-20,SRH,KKR,SRH,bat,KKR,29,21,21,15,0,4,"Eden Gardens, Kolkata"
8548,335983,2008,IPL,2008-04-19,PBKS,CSK,CSK,bat,CSK,50,50,8,50,1,0,"Punjab Cricket Association Stadium, Mohali, Ch..."
8549,335984,2008,IPL,2008-04-19,RR,DC,RR,bat,DC,50,50,50,6,1,3,"Feroz Shah Kotla, Delhi"
8550,335982,2008,IPL,2008-04-18,RCB,KKR,RCB,field,KKR,43,33,5,53,3,5,"M Chinnaswamy Stadium, Bengaluru"

In [4]:
df["team1"].unique()

array(['SRH', 'LSG', 'MI', 'RR', 'GT', 'KKR', 'PBKS', 'RCB', 'DC', 'RPS',
       'GL', 'PW', 'KTK'], dtype=object)

In [5]:
df["team2"].unique()

array(['RCB', 'GT', 'DC', 'CSK', 'LSG', 'PBKS', 'KKR', 'MI', 'RR', 'GL',
       'RPS', 'PW', 'KTK', 'SRH'], dtype=object)

In [6]:
df.isnull().sum()

match_id                 0
season                   0
event                    0
match_date               0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
winner                   0
h2h_team1_wins%          0
h2h_venue_team1_wins%    0
team1_venue_wins%        0
team2_venue_wins%        0
team1_last_5_wins        0
team2_last_5_wins        0
ground                   0
dtype: int64

In [7]:
df.columns

Index(['match_id', 'season', 'event', 'match_date', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'h2h_team1_wins%',
       'h2h_venue_team1_wins%', 'team1_venue_wins%', 'team2_venue_wins%',
       'team1_last_5_wins', 'team2_last_5_wins', 'ground'],
      dtype='object')

### **Feature Selection**

In [8]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

# Load the dataset

summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_cleaned.csv")

# Filter the DataFrame based on the event
summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])

# Split dataset into features (X) and target variable (y)
X = X_encoded.drop(columns=['match_id', 'season', 'match_date', "winner", "event_name", "event"])
y = pd.get_dummies(summary_df1['winner'])  # One-hot encoding for multi-class classification

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training
rf_model.fit(X_train, y_train)

# Get feature importances and sort them
feature_importances = rf_model.feature_importances_
sorted_indices = feature_importances.argsort()[::-1]  # Reverse order to get descending ranks

# Create a DataFrame to store feature names and their ranks
feature_ranks_df = pd.DataFrame({'Feature': X.columns[sorted_indices], 'Rank': range(1, len(X.columns) + 1)})

# Perform feature selection based on feature importances
selector = SelectFromModel(rf_model, threshold='median')
selector.fit(X_train, y_train)

# Transform the datasets to keep only selected features
X_train_selected = selector.transform(X_train)
X_test_selected = selector.transform(X_test)

# Print top 10 feature ranks
print("Top 10 Feature Ranks:")
feature_ranks_df.head(10)

Top 10 Feature Ranks:

                 Feature  Rank
0      team1_last_5_wins     1
1      team2_last_5_wins     2
2  h2h_venue_team1_wins%     3
3        h2h_team1_wins%     4
4      team2_venue_wins%     5
5      team1_venue_wins%     6
6              team2_CSK     7
7              team2_KKR     8
8               team2_DC     9
9              team1_SRH    10

### **Modelling**

### **Random Forest**

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, balanced_accuracy_score, f1_score

# Load the dataset
summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_cleaned.csv")

summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
le = LabelEncoder()
summary_df1['winner'] = le.fit_transform(summary_df1['winner'])

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])
X = X_encoded.drop(columns=[ 'match_id', 'season', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training - Random Forest
rf_model.fit(X_train, y_train)

# Model Evaluation - Random Forest
y_pred_rf = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Model Evaluation:")
print("--------------------------------------------------")
print(f"Random Forest Accuracy: {rf_accuracy * 100:.2f}%")
# Evaluate the model using advanced metrics
#print("Classification Report:")
#print(classification_report(y_test, y_pred_rf, zero_division=1))

#print("Confusion Matrix:")
#print(confusion_matrix(y_test, y_pred_rf))

#print("Balanced Accuracy Score:")
#balanced_acc = balanced_accuracy_score(y_test, y_pred_rf)
#print(f"Balanced Accuracy: {balanced_acc * 100:.2f}%")

#print("F1 Score:")
#f1 = f1_score(y_test, y_pred_rf, average='weighted')
#print(f"F1 Score: {f1 * 100:.2f}%")

Random Forest Model Evaluation:
--------------------------------------------------
Random Forest Accuracy: 67.53%

### **XGB Classifier**

In [10]:
# Ensure classes are encoded from 0 to n-1
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'], drop_first=True)
X = X_encoded.drop(columns=[ 'season',  'match_id', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Realign X to match indices of y (in case any indices were dropped)
X = X.loc[y.index]

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure y_train and y_test contain all classes
missing_classes = set(y.unique()) - set(y_train.unique())
for cls in missing_classes:
    X_train = pd.concat([X_train, X_test[y_test == cls]])
    y_train = pd.concat([y_train, y_test[y_test == cls]])

# Model Selection - XGBoost
xgb_model = XGBClassifier(eval_metric='mlogloss')

# Model Training - XGBoost
xgb_model.fit(X_train, y_train)

# Model Evaluation - XGBoost
y_pred_xgb = xgb_model.predict(X_test)
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("\nXGBoost Model Evaluation:")
print("--------------------------------------------------")
print(f"XGBoost Accuracy: {xgb_accuracy * 100:.2f}%")

XGBoost Model Evaluation:
--------------------------------------------------
XGBoost Accuracy: 70.13%

### **Teams**

In [11]:
# Assuming df is your DataFrame
sorted_teams = sorted(set(df["team1"].unique()).union(set(df["team2"].unique())))

# Create a string with team names side by side
side_by_side = ', '.join(sorted_teams)

side_by_side

'CSK, DC, GL, GT, KKR, KTK, LSG, MI, PBKS, PW, RCB, RPS, RR, SRH'

In [12]:
# Assuming df is your DataFrame
sorted_venues = sorted((df["ground"].unique()))

# Create a string with team names side by side

sorted_venues

['Arun Jaitley Stadium, Delhi',
 'Barabati Stadium, Cuttack',
 'Barsapara Cricket Stadium, Guwahati',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Brabourne Stadium, Mumbai',
 'Buffalo Park, East London',
 'De Beers Diamond Oval, Kimberley',
 'Dr Dy Patil Sports Academy, Mumbai, Navi Mumbai',
 'Dr. Y.S. Rajasekhara Reddy Aca-Vdca Cricket Stadium, Visakhapatnam',
 'Dubai International Cricket Stadium, Dubai',
 'Eden Gardens, Kolkata',
 'Feroz Shah Kotla, Delhi',
 'Green Park, Kanpur',
 'Himachal Pradesh Cricket Association Stadium, Dharmasala',
 'Holkar Cricket Stadium, Indore',
 'Jsca International Stadium Complex, Ranchi',
 'Kingsmead, Durban',
 'M Chinnaswamy Stadium, Bengaluru',
 'Ma Chidambaram Stadium, Chepauk, Chennai',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur, Mohali',
 'Maharashtra Cricket Association Stadium, Pune',
 'Narendra Modi Stadium, Ahmedabad',
 'Nehru Stadium, Kochi',
 'New Wanderers Stadium, Johannesburg',
 'Newlands, Cape Town',
 'Outsurance Oval, Bloemfontein',
 'Punjab Cricket Association Stadium, Mohali, Chandigarh',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'Sardar Patel (Gujarat) Stadium, Motera, Ahmedabad',
 'Saurashtra Cricket Association Stadium, Rajkot',
 'Sawai Mansingh Stadium, Jaipur',
 'Shaheed Veer Narayan Singh International Stadium, Raipur',
 'Sharjah Cricket Association Stadium, Sharjah',
 'Sheikh Zayed Stadium, Abu Dhabi',
 "St George'S Park, Port Elizabeth, Gqeberha",
 'Subrata Roy Sahara Stadium, Pune',
 'Supersport Park, Centurion',
 'Vidarbha Cricket Association Stadium, Jamtha, Nagpur',
 'Wankhede Stadium, Mumbai',
 'Zayed Cricket Stadium, Abu Dhabi']

### **Head-to-Head & Venue Wins**

In [13]:
h2h = df[((df["team1"] == "KKR") & (df["team2"] == "SRH")) | ((df["team1"] == "SRH") & (df["team2"] == "KKR"))  #& (df['ground'] == "Kensington Oval, Barbados, Bridgetown")
                  ].sort_values(by="match_date",ascending=False).reset_index(drop=True)
print("Matches:",len(h2h))
print("Team1 Won:",len(h2h[h2h["team1"] == h2h["winner"]]))

h2h[:10]

Matches: 38
Team1 Won: 11

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1473452,2025,IPL,2025-04-03,SRH,KKR,SRH,field,KKR,29,21,21,15,2,2,"Eden Gardens, Kolkata"
1,1426312,2024,IPL,2024-05-26,SRH,KKR,SRH,bat,KKR,29,0,0,50,3,3,"Ma Chidambaram Stadium, Chepauk, Chennai"
2,1426309,2024,IPL,2024-05-21,SRH,KKR,SRH,bat,KKR,29,0,0,50,3,4,"Narendra Modi Stadium, Ahmedabad"
3,1422121,2024,IPL,2024-03-23,SRH,KKR,SRH,field,KKR,29,21,21,15,1,3,"Eden Gardens, Kolkata"
4,1359521,2023,IPL,2023-05-04,SRH,KKR,KKR,bat,KKR,29,33,3,66,2,4,"Rajiv Gandhi International Stadium, Uppal, Hyd..."
5,1359493,2023,IPL,2023-04-14,SRH,KKR,KKR,field,SRH,29,21,21,15,2,3,"Eden Gardens, Kolkata"
6,1304107,2022,IPL,2022-05-14,SRH,KKR,KKR,bat,KKR,29,0,0,16,1,2,"Maharashtra Cricket Association Stadium, Pune"
7,1304071,2022,IPL,2022-04-15,SRH,KKR,SRH,field,SRH,29,100,20,0,2,2,"Brabourne Stadium, Mumbai"
8,1254109,2021,IPL,2021-10-03,SRH,KKR,SRH,bat,KKR,29,0,0,25,2,3,"Dubai International Cricket Stadium, Dubai"
9,1254060,2021,IPL,2021-04-11,SRH,KKR,SRH,field,KKR,29,0,0,50,4,3,"Ma Chidambaram Stadium, Chepauk, Chennai"

In [ ]:
print((df["team1"] == "SRH") & (df["ground"] == "Arun Jaitley Stadium, Delhi"))

1       False
3       False
5       False
7       False
8       False
        ...
8546    False
8547    False
8548    False
8549    False
8550    False
Length: 1152, dtype: bool

### **Prediction**

In [15]:
# Future match data
future_match = pd.DataFrame({
    'team1': h2h['team1'].unique(),
    'team2': h2h['team2'].unique(),
    'toss_winner': h2h['team1'].unique(),
    'toss_decision': ['bat'],
    'Ground': ['Arun Jaitley Stadium, Delhi'],
    'h2h_team1_wins%': [29],
    'h2h_venue_team1_wins%': [50],
    'team1_venue_wins%': [50],
    'team2_venue_wins%': [50],
    'team1_last_5_wins': [2],
    'team2_last_5_wins': [2]
})

# Encode categorical variables and ensure consistent columns with training data
future_match_encoded = pd.get_dummies(future_match, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'Ground'])

# Add missing columns for 'Ground' feature using the training data as a reference
missing_columns = list(set(X.columns) - set(future_match_encoded.columns))
future_match_encoded = pd.concat([future_match_encoded, pd.DataFrame(0, index=future_match_encoded.index, columns=missing_columns)], axis=1)

# Ensure all columns are in the correct order
future_match_encoded = future_match_encoded[X.columns]

# Make predictions for the future match
future_match_prediction = xgb_model.predict(future_match_encoded)

# Get the predicted winner's team name
predicted_winner_team_name = le.inverse_transform(future_match_prediction)[0]

print("Predicted Winner:", predicted_winner_team_name)

# Add prediction to the future_match DataFrame
future_match['predicted_winner'] = predicted_winner_team_name
future_match['actual_winner'] = " "

future_match.drop(columns=['h2h_team1_wins%', 'h2h_venue_team1_wins%', 'team1_venue_wins%','team2_venue_wins%', 'team1_last_5_wins', 'team2_last_5_wins'], inplace=True)

Predicted Winner: SRH

#### **Team1 Performance**

In [ ]:
team1_performance = df[((df["team1"] == "Zimbabwe") | (df["team2"] == "Zimbabwe")) #& (df['ground'] == 'Kensington Oval, Barbados, Bridgetown')
                      ].sort_values(by='match_date', ascending=False).reset_index(drop=True)
print("No of Matches: ", len(team1_performance))
team1_performance[:5]

#### **Team2 Performance**

In [ ]:
team2_performance = df[((df["team1"] == "India") | (df["team2"] == "India"))  #& (df['ground'] == 'Kensington Oval, Barbados, Bridgetown')
                       ].sort_values(by='match_date', ascending=False).reset_index(drop=True)
print("No of Matches: ", len(team2_performance))
team2_performance[:5]

In [ ]:
# Get unique grounds
grounds = summary_df1["ground"].unique()
grounds_set = set(grounds)

# Take input for the substring
substring = input("Enter the substring: ").strip().lower()

# Filter grounds that contain the given substring
filtered_grounds = [ground for ground in grounds_set if substring in ground.lower()]
                    #] #ground.lower().startswith(substring)

print("Filtered grounds:", filtered_grounds)