### **Genders Are male & female**

### **Match Types Are: ODI, T20, Test, MDM, ODM**

In [19]:
# Load the dataset
import pandas as pd


# Filter the DataFrame based on the match_type
match_type = input("Enter Match Type:")

# Filter the DataFrame based on the gender
gender = input("Enter Gender:")

In [20]:
import pandas as pd
df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type}_{gender.lower()}_match_summary_cleaned.csv")
df.drop(columns=["event_name"], inplace=True)
df = df[(df["winner"] == df["team1"]) | (df["winner"] == df["team2"])]
df.sort_values(by="match_date", ascending=False, ignore_index=True,inplace=True)
print("Length of Data Frame:", len(df))
df[:5]

Length of Data Frame: 8524

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1443087,2025,Big Bash League,2025-01-11,Brisbane Heat,Adelaide Strikers,Brisbane Heat,field,Adelaide Strikers,55,60,60,5,2,1,"Adelaide Oval, Adelaide"
1,1443086,2025,Big Bash League,2025-01-11,Sydney Sixers,Perth Scorchers,Perth Scorchers,field,Sydney Sixers,41,58,13,41,3,2,"Sydney Cricket Ground, Sydney"
2,1449636,2025,SA20,2025-01-11,Sunrisers Eastern Cape,Paarl Royals,Sunrisers Eastern Cape,bat,Paarl Royals,60,66,66,20,4,2,"Boland Bank Park, Paarl"
3,1459552,2025,Bangladesh Premier League,2025-01-10,Dhaka Capital,Sylhet Strikers,Dhaka Capital,bat,Sylhet Strikers,0,0,0,100,0,2,"Sylhet International Cricket Stadium, Academy ..."
4,1459551,2025,Bangladesh Premier League,2025-01-10,Durbar Rajshahi,Khulna Tigers,Khulna Tigers,field,Durbar Rajshahi,100,100,100,0,1,3,"Sylhet International Cricket Stadium, Academy ..."

In [21]:
df["event"].unique()

array(['Big Bash League', 'SA20', 'Bangladesh Premier League',
       'Super Smash', 'T20I', 'Nepal Premier League',
       'Syed Mushtaq Ali Trophy', 'CSA T20 Challenge',
       'Caribbean Premier League',
       "ICC Men's T20 World Cup Sub Regional Africa Qualifier",
       'Vitality Blast',
       'Cricket Ireland Inter-Provincial Twenty20 Trophy',
       "The Hundred Men's Competition", 'Major League Cricket',
       'Lanka Premier League', 'IPL', 'Pakistan Super League',
       'International League T20', 'Mzansi Super League'], dtype=object)

In [22]:
# Filter the DataFrame based on the event
event = input("Enter Event Name: ")

In [23]:
df = df[(df["event"]  == event)]
print("Length of Data Frame: ",len(df))
df[:5]

Length of Data Frame:  596

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1443087,2025,Big Bash League,2025-01-11,Brisbane Heat,Adelaide Strikers,Brisbane Heat,field,Adelaide Strikers,55,60,60,5,2,1,"Adelaide Oval, Adelaide"
1,1443086,2025,Big Bash League,2025-01-11,Sydney Sixers,Perth Scorchers,Perth Scorchers,field,Sydney Sixers,41,58,13,41,3,2,"Sydney Cricket Ground, Sydney"
5,1443085,2025,Big Bash League,2025-01-10,Sydney Thunder,Hobart Hurricanes,Hobart Hurricanes,field,Hobart Hurricanes,42,20,20,18,3,4,"Bellerive Oval, Hobart"
11,1443084,2025,Big Bash League,2025-01-09,Sydney Sixers,Melbourne Stars,Sydney Sixers,field,Melbourne Stars,65,63,58,14,4,2,"Melbourne Cricket Ground, Melbourne"
14,1443082,2025,Big Bash League,2025-01-07,Perth Scorchers,Melbourne Renegades,Melbourne Renegades,field,Melbourne Renegades,76,66,14,33,2,2,"Perth Stadium, Perth"

In [24]:
df["team2"].unique()

array(['Adelaide Strikers', 'Perth Scorchers', 'Hobart Hurricanes',
       'Melbourne Stars', 'Melbourne Renegades', 'Brisbane Heat',
       'Sydney Sixers'], dtype=object)

In [25]:
df.isnull().sum()

match_id                 0
season                   0
event                    0
match_date               0
team1                    0
team2                    0
toss_winner              0
toss_decision            0
winner                   0
h2h_team1_wins%          0
h2h_venue_team1_wins%    0
team1_venue_wins%        0
team2_venue_wins%        0
team1_last_5_wins        0
team2_last_5_wins        0
ground                   0
dtype: int64

In [26]:
df.columns

Index(['match_id', 'season', 'event', 'match_date', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'h2h_team1_wins%',
       'h2h_venue_team1_wins%', 'team1_venue_wins%', 'team2_venue_wins%',
       'team1_last_5_wins', 'team2_last_5_wins', 'ground'],
      dtype='object')

### **Feature Selection**

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

# Load the dataset

summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_cleaned.csv")

# Filter the DataFrame based on the event
summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])

# Split dataset into features (X) and target variable (y)
X = X_encoded.drop(columns=['match_id', 'season', 'match_date', "winner", "event_name", "event"])
y = pd.get_dummies(summary_df1['winner'])  # One-hot encoding for multi-class classification

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training
rf_model.fit(X_train, y_train)

# Get feature importances and sort them
feature_importances = rf_model.feature_importances_
sorted_indices = feature_importances.argsort()[::-1]  # Reverse order to get descending ranks

# Create a DataFrame to store feature names and their ranks
feature_ranks_df = pd.DataFrame({'Feature': X.columns[sorted_indices], 'Rank': range(1, len(X.columns) + 1)})

# Perform feature selection based on feature importances
selector = SelectFromModel(rf_model, threshold='median')
selector.fit(X_train, y_train)

# Transform the datasets to keep only selected features
X_train_selected = selector.transform(X_train)
X_test_selected = selector.transform(X_test)

# Print top 10 feature ranks
print("Top 10 Feature Ranks:")
feature_ranks_df.head(10)

Top 10 Feature Ranks:

                   Feature  Rank
0        team1_last_5_wins     1
1        team2_last_5_wins     2
2          h2h_team1_wins%     3
3    h2h_venue_team1_wins%     4
4        team2_venue_wins%     5
5      team1_Sydney Sixers     6
6        team1_venue_wins%     7
7    team1_Perth Scorchers     8
8  team2_Adelaide Strikers     9
9      toss_decision_field    10

### **Modelling**

### **Random Forest**

In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix, balanced_accuracy_score, f1_score

# Load the dataset
summary_df = pd.read_csv(fr"D:\GITHUB\Predictive-Analytics-for-Cricket-Matches-Using-Machine-Learning\source_data\Summary\match_summary\{gender}\{match_type.title()}_{gender.lower()}_match_summary_cleaned.csv")

summary_df1 = summary_df[summary_df["event"] == event].copy()

# Encode categorical variables
le = LabelEncoder()
summary_df1['winner'] = le.fit_transform(summary_df1['winner'])

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'])
X = X_encoded.drop(columns=[ 'match_id', 'season', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Selection - Random Forest
rf_model = RandomForestClassifier()

# Model Training - Random Forest
rf_model.fit(X_train, y_train)

# Model Evaluation - Random Forest
y_pred_rf = rf_model.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Model Evaluation:")
print("--------------------------------------------------")
print(f"Random Forest Accuracy: {rf_accuracy * 100:.2f}%")
# Evaluate the model using advanced metrics
#print("Classification Report:")
#print(classification_report(y_test, y_pred_rf, zero_division=1))

#print("Confusion Matrix:")
#print(confusion_matrix(y_test, y_pred_rf))

#print("Balanced Accuracy Score:")
#balanced_acc = balanced_accuracy_score(y_test, y_pred_rf)
#print(f"Balanced Accuracy: {balanced_acc * 100:.2f}%")

#print("F1 Score:")
#f1 = f1_score(y_test, y_pred_rf, average='weighted')
#print(f"F1 Score: {f1 * 100:.2f}%")

Random Forest Model Evaluation:
--------------------------------------------------
Random Forest Accuracy: 60.00%

### **XGB Classifier**

In [29]:
# Ensure classes are encoded from 0 to n-1
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

# Split dataset into features (X) and target variable (y)
X_encoded = pd.get_dummies(summary_df1, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'ground'], drop_first=True)
X = X_encoded.drop(columns=[ 'season',  'match_id', 'match_date', "winner", 'event_name', 'event'])
y = summary_df1['winner']

# Realign X to match indices of y (in case any indices were dropped)
X = X.loc[y.index]

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure y_train and y_test contain all classes
missing_classes = set(y.unique()) - set(y_train.unique())
for cls in missing_classes:
    X_train = pd.concat([X_train, X_test[y_test == cls]])
    y_train = pd.concat([y_train, y_test[y_test == cls]])

# Model Selection - XGBoost
xgb_model = XGBClassifier(eval_metric='mlogloss')

# Model Training - XGBoost
xgb_model.fit(X_train, y_train)

# Model Evaluation - XGBoost
y_pred_xgb = xgb_model.predict(X_test)
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)

print("\nXGBoost Model Evaluation:")
print("--------------------------------------------------")
print(f"XGBoost Accuracy: {xgb_accuracy * 100:.2f}%")

XGBoost Model Evaluation:
--------------------------------------------------
XGBoost Accuracy: 64.17%

### **Teams**

In [30]:
# Assuming df is your DataFrame
sorted_teams = sorted(set(df["team1"].unique()).union(set(df["team2"].unique())))

# Create a string with team names side by side
side_by_side = ', '.join(sorted_teams)

side_by_side

'Adelaide Strikers, Brisbane Heat, Hobart Hurricanes, Melbourne Renegades, Melbourne Stars, Perth Scorchers, Sydney Sixers, Sydney Thunder'

### **Head-to-Head & Venue Wins**

In [31]:
h2h = df[((df["team1"] == "Melbourne Stars") & (df["team2"] == "Melbourne Renegades")) | ((df["team1"] == "Melbourne Renegades") & (df["team2"] == "Melbourne Stars"))  #& (df['ground'] == "Kensington Oval, Barbados, Bridgetown")
                  ].sort_values(by="match_date",ascending=False).reset_index(drop=True)
print("Matches:",len(h2h))
print("Team1 Won:",len(h2h[h2h["team1"] == h2h["winner"]]))

h2h[:10]

Matches: 26
Team1 Won: 16

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1443079,2025,Big Bash League,2025-01-04,Melbourne Stars,Melbourne Renegades,Melbourne Stars,field,Melbourne Stars,62,61,21,35,2,2,"Melbourne Cricket Ground, Melbourne"
1,1386129,2024,Big Bash League,2024-01-13,Melbourne Stars,Melbourne Renegades,Melbourne Renegades,field,Melbourne Renegades,62,61,61,14,0,2,"Docklands Stadium, Melbourne"
2,1386116,2024,Big Bash League,2024-01-02,Melbourne Stars,Melbourne Renegades,Melbourne Stars,field,Melbourne Stars,62,61,21,35,1,2,"Melbourne Cricket Ground, Melbourne"
3,1324664,2023,Big Bash League,2023-01-14,Melbourne Stars,Melbourne Renegades,Melbourne Stars,field,Melbourne Renegades,62,61,61,14,2,1,"Docklands Stadium, Melbourne"
4,1324650,2023,Big Bash League,2023-01-03,Melbourne Stars,Melbourne Renegades,Melbourne Stars,field,Melbourne Renegades,62,61,21,35,0,1,"Melbourne Cricket Ground, Melbourne"
5,1269685,2022,Big Bash League,2022-01-13,Melbourne Stars,Melbourne Renegades,Melbourne Renegades,bat,Melbourne Stars,62,61,61,14,1,3,"Docklands Stadium, Melbourne"
6,1269670,2022,Big Bash League,2022-01-03,Melbourne Stars,Melbourne Renegades,Melbourne Stars,bat,Melbourne Renegades,62,61,21,35,1,1,"Melbourne Cricket Ground, Melbourne"
7,1226869,2021,Big Bash League,2021-01-20,Melbourne Stars,Melbourne Renegades,Melbourne Stars,bat,Melbourne Renegades,62,61,61,14,3,3,"Docklands Stadium, Melbourne"
8,1226864,2021,Big Bash League,2021-01-17,Melbourne Stars,Melbourne Renegades,Melbourne Renegades,bat,Melbourne Stars,62,61,21,35,3,2,"Melbourne Cricket Ground, Melbourne"
9,1195602,2020,Big Bash League,2020-01-10,Melbourne Stars,Melbourne Renegades,Melbourne Stars,field,Melbourne Stars,62,61,61,14,2,2,"Docklands Stadium, Melbourne"

### **Prediction**

In [33]:
# Future match data
future_match = pd.DataFrame({
    'team1': ['Melbourne Stars'],
    'team2': ['Melbourne Renegades'],
    'toss_winner': ['Melbourne Stars'],
    'toss_decision': ['field'],
    'Ground': ['Docklands Stadium, Melbourne'],
    'h2h_team1_wins%': [62],
    'h2h_venue_team1_wins%': [61],
    'team1_venue_wins%': [61],
    'team2_venue_wins%': [14],
    'team1_last_5_wins': [2],
    'team2_last_5_wins': [2]
})

# Encode categorical variables and ensure consistent columns with training data
future_match_encoded = pd.get_dummies(future_match, columns=['team1', 'team2', 'toss_winner', 'toss_decision', 'Ground'])

# Add missing columns for 'Ground' feature using the training data as a reference
missing_columns = list(set(X.columns) - set(future_match_encoded.columns))
future_match_encoded = pd.concat([future_match_encoded, pd.DataFrame(0, index=future_match_encoded.index, columns=missing_columns)], axis=1)

# Ensure all columns are in the correct order
future_match_encoded = future_match_encoded[X.columns]

# Make predictions for the future match
future_match_prediction = xgb_model.predict(future_match_encoded)

# Get the predicted winner's team name
predicted_winner_team_name = le.inverse_transform(future_match_prediction)[0]

print("Predicted Winner:", predicted_winner_team_name)

# Add prediction to the future_match DataFrame
future_match['predicted_winner'] = predicted_winner_team_name
future_match['actual_winner'] = " "

future_match.drop(columns=['h2h_team1_wins%', 'h2h_venue_team1_wins%', 'team1_venue_wins%','team2_venue_wins%', 'team1_last_5_wins', 'team2_last_5_wins'], inplace=True)

Predicted Winner: Melbourne Renegades

#### **Team1 Performance**

In [16]:
team1_performance = df[((df["team1"] == "Zimbabwe") | (df["team2"] == "Zimbabwe")) #& (df['ground'] == 'Kensington Oval, Barbados, Bridgetown')
                      ].sort_values(by='match_date', ascending=False).reset_index(drop=True)
print("No of Matches: ", len(team1_performance))
team1_performance[:5]

No of Matches:  144

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1425130,2024,T20I,2024-05-12,Zimbabwe,Bangladesh,Zimbabwe,field,Zimbabwe,33,28,25,14,1,3,"Shere Bangla National Stadium, Mirpur, Dhaka"
1,1425129,2024,T20I,2024-05-10,Zimbabwe,Bangladesh,Zimbabwe,field,Bangladesh,33,28,25,14,2,2,"Shere Bangla National Stadium, Mirpur, Dhaka"
2,1425128,2024,T20I,2024-05-07,Zimbabwe,Bangladesh,Zimbabwe,field,Bangladesh,33,0,0,33,3,2,"Zahur Ahmed Chowdhury Stadium, Chittagong, Cha..."
3,1425127,2024,T20I,2024-05-05,Zimbabwe,Bangladesh,Bangladesh,field,Bangladesh,33,0,0,33,4,2,"Zahur Ahmed Chowdhury Stadium, Chittagong, Cha..."
4,1425126,2024,T20I,2024-05-03,Zimbabwe,Bangladesh,Bangladesh,field,Bangladesh,33,0,0,33,5,2,"Zahur Ahmed Chowdhury Stadium, Chittagong, Cha..."

#### **Team2 Performance**

In [17]:
team2_performance = df[((df["team1"] == "India") | (df["team2"] == "India"))  #& (df['ground'] == 'Kensington Oval, Barbados, Bridgetown')
                       ].sort_values(by='match_date', ascending=False).reset_index(drop=True)
print("No of Matches: ", len(team2_performance))
team2_performance[:5]

No of Matches:  219

,match_id,season,event,match_date,team1,team2,toss_winner,toss_decision,winner,h2h_team1_wins%,h2h_venue_team1_wins%,team1_venue_wins%,team2_venue_wins%,team1_last_5_wins,team2_last_5_wins,ground
0,1415755,2024,T20I,2024-06-29,South Africa,India,India,bat,India,42,0,0,50,5,5,"Kensington Oval, Barbados, Bridgetown"
1,1415754,2024,T20I,2024-06-27,India,England,England,field,India,54,100,100,0,5,4,"Providence Stadium, Guyana, Providence"
2,1415751,2024,T20I,2024-06-24,India,Australia,Australia,field,India,65,100,100,0,5,4,"Darren Sammy National Cricket Stadium, Gros Is..."
3,1415747,2024,T20I,2024-06-22,India,Bangladesh,Bangladesh,field,India,93,100,100,0,5,4,"Sir Vivian Richards Stadium, North Sound, Antigua"
4,1415743,2024,T20I,2024-06-20,India,Afghanistan,India,bat,India,100,100,50,0,5,1,"Kensington Oval, Barbados, Bridgetown"

In [14]:
# Get unique grounds
grounds = summary_df1["ground"].unique()
grounds_set = set(grounds)

# Take input for the substring
substring = input("Enter the substring: ").strip().lower()

# Filter grounds that contain the given substring
filtered_grounds = [ground for ground in grounds_set if substring in ground.lower()]
                    #] #ground.lower().startswith(substring)

print("Filtered grounds:", filtered_grounds)

Filtered grounds: ['Kensington Oval, Barbados, Bridgetown', 'Trent Bridge, Nottingham']